apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: provisioning-backend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: provisioning-backend
    app.kubernetes.io/part-of: provisioning-backend
  name: provisioning-backend
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: provisioning-backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: provisioning-backend
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-hms-tenant/provisioning-backend/provisioning-backend@sha256:8e0c324aeab56f6c700fd4f996146adeb8cd344782a1235b48661080b3c112f8
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
