apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: provisioning-backend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: provisioning-backend
    app.kubernetes.io/part-of: provisioning-backend
  name: provisioning-backend
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: provisioning-backend
status:
  loadBalancer: {}
